{ ... }: [
  #"bitwarden" # needs to be installed through MAS..else browser integration doesn't work!
  "raycast"
  "balenaetcher"
  #"slack" # replaced with MAS version
  "discord"
  "etrecheckpro"
  "logi-options-plus"
  "notunes"
  "obsidian"
  "spotify"
  "telegram"
  "whatsapp"
  "pycharm-ce"
  "visual-studio-code"
  "zoom"
  "docker"
  "intellij-idea-ce"
  "licecap"
  "studio-3t"
  "postman"
  "goland"
  "chromium"
  "pgadmin4"
]
